# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f0a4a5d1a11fd7aba1d3e7504e60d029901ef3f515508da8d0bee8b853cee74e32184a1a7db9203ff034e137e8b9b6ef175a3de2678c6a24bc36be32198624f

test:
  secret_key_base: 283f8487abc52646f33f7e1abbef3e61c18dbc41ad41c5311eb49953527f92ef43746c2df43d93aa500ea686f605422ed2bdb056e625a596f1322b95748369bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
